export const CATEGORIES = [
{
    id: 'muze-gezisi',
    title: 'Müze Gezisi',
    description: 'Müzeleri keşfedin',
    emoji: '🖼️',
    color: '#4A7C9E',
  },
  {
    id: 'tarihi-gezi',
    title: 'Tarihi Gezi',
    description: 'Tarihi yerleri keşfedin',
    emoji: '🏛️',
    color: '#4A7C9E',
  },
  {
    id: 'restoranlar',
    title: 'Restoranlar',
    description: 'Yemek mekanları',
    emoji: '🍴',
    color: '#5B7C6A',
    subFilters: [
      { label: '🍔 Burger', keyword: 'burger' },
      { label: '🍕 Pizza', keyword: 'pizza' },
      { label: '🥙 Kebap', keyword: 'kebap' },
      { label: '🫓 Pide', keyword: 'pide' },
      { label: '🐟 Balık', keyword: 'balık' },
      { label: '🍣 Sushi', keyword: 'sushi' },
      { label: '🫓 Döner', keyword: 'döner' },
    ],
  },
  {
    id: 'kahve-brunch',
    title: 'Kahve & Brunch',
    description: 'Kafe ve brunch mekanları',
    emoji: '☕',
    color: '#F5EDE0',
    subFilters: [
      { label: '☕ Kahve', keyword: 'kahve', types: ['cafe', 'coffee_shop'] },
      { label: '🍰 Tatlı', keyword: 'tatlı', types: ['cafe', 'bakery'] },
      { label: '🥐 Pastane', keyword: 'pastane', types: ['bakery'] },
      { label: '🍞 Fırın', keyword: 'fırın', types: ['bakery'] },
    ],
  },
  {
    id: 'publar',
    title: 'Publar',
    description: 'Bar ve pub mekanları',
    emoji: '🍻',
    color: '#E07A5F',
  },
  {
    id: 'otel',
    title: 'Otel Önerileri',
    description: 'Konaklama seçenekleri',
    emoji: '🏨',
    color: '#E07A5F',
  },
  {
    id: 'sahiller',
    title: 'Plajlar & Sahiller',
    description: 'Deniz ve plaj keyfi',
    emoji: '🏖️',
    color: '#A8DADC',
  },
  {
    id: 'doga-yuruyusu',
    title: 'Doğa Yürüyüşü',
    description: 'Parklar ve doğa rotaları',
    emoji: '🥾',
    color: '#5B7C6A',
  },
  {
    id: 'kamp',
    title: 'Kamp Yapılacak Yerler',
    description: 'Kamp alanlarını keşfedin',
    emoji: '⛺',
    color: '#A8DADC',
  },
  {
    id: 'benzin-istasyonu',
    title: 'Benzin İstasyonu',
    description: 'Yakındaki benzin istasyonları',
    emoji: '⛽',
    color: '#4A7C9E',
  },
  {
    id: 'park',
    title: 'Park',
    description: 'Yakındaki parklar',
    emoji: '🌳',
    color: '#5B7C6A',
  },
  {
    id: 'supermarket',
    title: 'Süpermarket',
    description: 'Yakındaki marketler',
    emoji: '🛒',
    color: '#4A7C9E',
  },
];
